### ISSUE TITLE
설명 부분에 줄바꿈을 추가해주세요!

### ISSUE THREAD

**Issue by sumi-0011** [sjoleee/very-simple-portfolio#1]
## 개선 사항
밑과 같이 설명 부분에 줄바꿈을 할 수 있으면 좋겠습니다. 

전

> 오직 나만을 위한 맛집 검색 내 입맛대로 Preat, 사람들의 입맛 정보를 수집/가공하여 각자의 취향에 맞는 private한 정보를 제공하는  맛집 검색 서비스

> 오직 나만을 위한 맛집 검색 내 입맛대로 Preat
사람들의 입맛 정보를 수집/가공하여 각자의 취향에 맞는 private한 정보를 제공하는  맛집 검색 서비스

### 스크린샷
<img width="752" alt="스크린샷 2023-05-17 오전 2 48 44" src="https://github.com/sjoleee/very-simple-portfolio/assets/49177223/f7a9f878-2ae5-4797-9d3d-ed0a4537aaaf">

**Comment by sjoleee** [comment]
의견 감사드립니다! 기능 추가했으니 많이 사용해주세요~~!

**Comment by sumi-0011** [comment]
감사합니다!
