### ISSUE TITLE
Vercel Analytics 대신 GA를 사용하신 이유가 있을까여?

### ISSUE THREAD

**Issue by snowriceDD** [sjoleee/very-simple-portfolio#5]
물론 GA가 레포트를 더 상세히 만들어 주긴 합니다.

포트폴리오 웹 기준으로 단순히 동접자, 방문 페이지 정도를 조회하는 기능으로는 
vercel에서 기본적으로 제공하는 analytics를 사용해도 괜찮을 것 같아서 의견을 여쭈어봅니다!

특별한 이유가 있어 GA를 선정하신 것인지,
아니면 개인의 취향에 따라서 선택하면 되는 부분인지 답변주시면 감사하겠습니다!

**Comment by sjoleee** [comment]
안녕하세요!

결론을 말씀드리자면 특별한 이유는 없습니다 ㅋㅋㅋㅋ
제가 예전부터 GA를 사용해오고 있어서, 여러 앱을 한 구글계정에 등록해놓고 편하게 보려고 GA를 선택한 것 뿐이에요
(실시간 방문자 지도에 찍어주는걸 보고있으면 재밌기도 합니다 하하..)

원하시는 대로 커스텀하셔서 사용하시면 되겠습니당!
관심 가져주셔서 감사해요 🙇‍♂️

**Comment by snowriceDD** [comment]
아하 ㅋㅋㅋ 역시.. 직무 상 애널리틱스 경험이 많으실 것 같아요 ㅋㅋ
답변 감사합니다!
